id: IAAAE3AA4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T03:13:35+00:00'
last_modified: '2022-06-08T11:54:14.898540+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29143
  title: གཅོད་པ་དོན་གྲུབ་དང་སྙིང་པོ་ཚེ་རིང་གི་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '8658':
      image_group_id: I00KG08137
      title: ''
      total_pages: 540
      order: 1
      base_file: 8658.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
